FROM ubuntu:16.04


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates openssh-server wget postfix

RUN wget https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh && chmod 777 script.deb.sh && ./script.deb.sh && apt-get install -y gitlab-ce

RUN apt update && apt install -y tzdata && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 443 80 22

#RUN mkdir -p /etc/gitlab/ssl
#RUN chmod 700 /etc/gitlab/ssl
#RUN openssl req -new -x509 -days 365 -nodes -out gitlab.example.com.crt -keyout gitlab.example.com.key -subj "/C=FR/ST=Paris/L=Paris/O=42/OU/Docker_project/CN=gitlab"
#RUN cp gitlab.example.com.key gitlab.example.com.crt /etc/gitlab/ssl/

#RUN gitlab-ctl reconfigure

#ENTRYPOINT (/opt/gitlab/embedded/bin/runsvdir-start &) && gitlab-ctl reconfigure && tail -f /dev/null